import type { InputInfo } from '../src/checks/inputs';

export interface RegistryEntry { tag: string; className: string; version: string; inputs: InputInfo[]; sample: Record<string, unknown> }

/** A literal as an Angular template expression (single quotes: the binding sits in a double-quoted attribute). */
export function templateLiteral(v: unknown): string {
  if (v === null) return 'null';
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) return `[${v.map(templateLiteral).join(', ')}]`;
  if (typeof v === 'object') return `{ ${Object.entries(v as Record<string, unknown>).map(([k, x]) => `${JSON.stringify(k)}: ${templateLiteral(x)}`).join(', ')} }`;
  throw new Error(`not a literal: ${String(v)}`);
}
/** A literal as TypeScript source: single quotes, bare keys where they are identifiers. */
function jsLiteral(v: unknown): string {
  if (Array.isArray(v)) return `[${v.map(jsLiteral).join(', ')}]`;
  if (v && typeof v === 'object') {
    const e = Object.entries(v as Record<string, unknown>);
    return e.length ? `{ ${e.map(([k, x]) => `${/^[A-Za-z_$][\w$]*$/.test(k) ? k : templateLiteral(k)}: ${jsLiteral(x)}`).join(', ')} }` : '{}';
  }
  return templateLiteral(v);
}

/** `src/site/registry.generated.ts`: PtSlot (one `@defer (hydrate on viewport)` case per component, literal defaults) and REGISTRY. */
export function registrySource(entries: RegistryEntry[]): string {
  const list = [...entries].sort((a, b) => (a.tag < b.tag ? -1 : 1));
  const binding = (i: InputInfo) => `[${i.name}]="$any(p()).${i.name}${'default' in i ? ` ?? ${templateLiteral(i.default)}` : ''}"`;
  return `// Generated by scripts/registry.ts from components/*.ts — do not edit. Each placement is its own incremental-hydration boundary
// (\`@defer (hydrate on viewport)\`) and lazy chunk; a prop the page does not give gets the component's own (literal) default.
import { Component, computed, inject, Injector, input } from '@angular/core';
import { Pt, PT_SLOT } from '@pretickt/components/context';
${list.map((e) => `import { ${e.className} } from '../../components/${e.tag}';`).join('\n')}

/** Every component: its version, and props it can render with (the build renders each once before any page, see warmUp). */
export const REGISTRY: Record<string, { version: string; sample: Record<string, unknown> }> = {
${list.map((e) => `  '${e.tag}': { version: '${e.version}', sample: ${jsLiteral(e.sample)} },`).join('\n')}
};

/** One placement: the island wrapper (\`tag@version\` for the beacon, the error notice) and its component, hydrated when it scrolls into view. */
@Component({
  selector: 'div[ptSlot]',
  imports: [${list.map((e) => e.className).join(', ')}],
  providers: [Pt, { provide: PT_SLOT, useFactory: () => { const injector = inject(Injector); return () => injector.get(PtSlot).id(); } }],
  host: { class: 'pt-island', '[attr.data-island]': 'id()', '[class.pt-island-error]': 'pt.failed()' },
  template: \`
    @switch (c()) {
${list.map((e) => `      @case ('${e.tag}') { @defer (hydrate on viewport) {<${e.tag} ${e.inputs.map(binding).join(' ')} />} }`).join('\n')}
    }\`,
})
export class PtSlot {
  readonly c = input.required<string>();
  readonly p = input.required<Record<string, unknown>>();
  protected readonly pt = inject(Pt);
  readonly id = computed(() => \`\${this.c()}@\${REGISTRY[this.c()]?.version ?? '0.0.0'}\`);
}
`;
}
