// Generated by scripts/registry.ts from components/*.ts — do not edit. Each placement is its own incremental-hydration boundary
// (`@defer (hydrate on viewport)`) and lazy chunk; a prop the page does not give gets the component's own (literal) default.
import { Component, computed, inject, Injector, input } from '@angular/core';
import { Pt, PT_SLOT } from '@pretickt/components/context';
import { PtCalendar } from '../../components/pt-calendar';
import { PtCompanyCard } from '../../components/pt-company-card';
import { PtFinancials } from '../../components/pt-financials';
import { PtInsiders } from '../../components/pt-insiders';
import { PtMetric } from '../../components/pt-metric';
import { PtNews } from '../../components/pt-news';
import { PtPriceEvents } from '../../components/pt-price-events';
import { PtPriceTarget } from '../../components/pt-price-target';
import { PtScreen } from '../../components/pt-screen';
import { PtWhyToday } from '../../components/pt-why-today';

/** Every component: its version, and props it can render with (the build renders each once before any page, see warmUp). */
export const REGISTRY: Record<string, { version: string; sample: Record<string, unknown> }> = {
  'pt-calendar': { version: '2.4.0', sample: { month: '2026-09' } },
  'pt-company-card': { version: '1.1.0', sample: { ticker: 'NVDA' } },
  'pt-financials': { version: '2.2.0', sample: { ticker: 'NVDA' } },
  'pt-insiders': { version: '2.2.0', sample: { ticker: 'NVDA' } },
  'pt-metric': { version: '2.1.0', sample: { ticker: 'NVDA', metrics: ['pe', 'rsi14'] } },
  'pt-news': { version: '2.1.0', sample: { ticker: 'NVDA' } },
  'pt-price-events': { version: '2.1.0', sample: { ticker: 'NVDA' } },
  'pt-price-target': { version: '2.1.0', sample: { ticker: 'NVDA' } },
  'pt-screen': { version: '2.3.0', sample: { list: 'biggest_losers' } },
  'pt-why-today': { version: '2.1.0', sample: { ticker: 'NVDA' } },
};

/** One placement: the island wrapper (`tag@version` for the beacon, the error notice) and its component, hydrated when it scrolls into view. */
@Component({
  selector: 'div[ptSlot]',
  imports: [PtCalendar, PtCompanyCard, PtFinancials, PtInsiders, PtMetric, PtNews, PtPriceEvents, PtPriceTarget, PtScreen, PtWhyToday],
  providers: [Pt, { provide: PT_SLOT, useFactory: () => { const injector = inject(Injector); return () => injector.get(PtSlot).id(); } }],
  host: { class: 'pt-island', '[attr.data-island]': 'id()', '[class.pt-island-error]': 'pt.failed()' },
  template: `
    @switch (c()) {
      @case ('pt-calendar') { @defer (hydrate on viewport) {<pt-calendar [month]="$any(p()).month" [kind]="$any(p()).kind ?? 'earnings'" [view]="$any(p()).view ?? 'month'" [start]="$any(p()).start" />} }
      @case ('pt-company-card') { @defer (hydrate on viewport) {<pt-company-card [ticker]="$any(p()).ticker" [size]="$any(p()).size ?? 'wide'" [extra]="$any(p()).extra ?? null" />} }
      @case ('pt-financials') { @defer (hydrate on viewport) {<pt-financials [ticker]="$any(p()).ticker" [periods]="$any(p()).periods ?? 8" />} }
      @case ('pt-insiders') { @defer (hydrate on viewport) {<pt-insiders [ticker]="$any(p()).ticker" [days]="$any(p()).days ?? 365" />} }
      @case ('pt-metric') { @defer (hydrate on viewport) {<pt-metric [ticker]="$any(p()).ticker" [metrics]="$any(p()).metrics" />} }
      @case ('pt-news') { @defer (hydrate on viewport) {<pt-news [ticker]="$any(p()).ticker" [limit]="$any(p()).limit ?? 20" />} }
      @case ('pt-price-events') { @defer (hydrate on viewport) {<pt-price-events [ticker]="$any(p()).ticker" [range]="$any(p()).range ?? '1y'" />} }
      @case ('pt-price-target') { @defer (hydrate on viewport) {<pt-price-target [ticker]="$any(p()).ticker" />} }
      @case ('pt-screen') { @defer (hydrate on viewport) {<pt-screen [list]="$any(p()).list" [peersOf]="$any(p()).peersOf" [limit]="$any(p()).limit ?? 25" />} }
      @case ('pt-why-today') { @defer (hydrate on viewport) {<pt-why-today [ticker]="$any(p()).ticker" [window]="$any(p()).window ?? '1d'" />} }
    }`,
})
export class PtSlot {
  readonly c = input.required<string>();
  readonly p = input.required<Record<string, unknown>>();
  protected readonly pt = inject(Pt);
  readonly id = computed(() => `${this.c()}@${REGISTRY[this.c()]?.version ?? '0.0.0'}`);
}
